---
    - hosts: all 
      become: yes
      become_user: root
    #  ansible_become_pass: 
      tasks:
      - name: Remove old Docker pkgs
        apt:
          name:
            - docker
            - docker-engine 
            - docker.io 
            - containerd 
            - runc
          state: absent 
      - name: Install latest version of "docker" 
        apt:
          pkg:
            - apt-transport-https 
            - ca-certificates 
            - curl 
            - gnupg-agent 
            - software-properties-common 
            - git
      - name: add Docker repo keys
        shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
      - name: apt-key fingerprint 
        shell: apt-key fingerprint 0EBFCD88
      - name: add repos
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present
      - name: apt update
        apt: 
          update_cache: yes
      - name: apt install docker
        apt:
          pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io      
    #  - name: create group Docker
     #   shell: groupadd docker
     ### optional , let ubuntu user use docker w/o sudo
     # - name: add ubuntu user to group docker
     #   shell: usermod -a -G docker ubuntu
     # - name: test if docker is installed and ubuntu can run it w/o sudo babyyy
        shell: docker ps 
